### ISSUE TITLE
Refresh of errors and autocompletion in vscode when .module.scss.d.ts files are changed.

### ISSUE THREAD

**Issue by boformer** [skovy/typed-scss-modules#113]
## Expected Behavior

Once the .module.scss.d.ts files are recompiled (either in watch mode or manually), vscode should immediately start autocompleting newly added class names. no errors should be shown when those new class names are used in .tsx files.

## Current Behavior
The TS language service doesn't seem to be aware that a .d.ts file has changed, the suggestions and 
Autocomplete suggestions and types known by the only get refreshed after about 30s (in a large project), or once you open the .module.scss.d.ts file

## Possible Solution

I suppose we would somehow have to tell the typescript language service that a .d.ts files has updated?

https://github.com/Microsoft/TypeScript/wiki/Writing-a-Language-Service-Plugin

## Steps to Reproduce (for bugs)

- In a TypeScript react project, create a .tsx file and a .module.scss file.
- Generate the module definitions with tsm and import the scss module into the .tsx file (`import styles from ...`)
- Close all open files in vscode except the .scss and .tsx file
- Add a new class name in the .scss file and regenerate the module definitions, e.g. `.myClass`
- switch to the .tsx file and try to use the new class name and check if the autocomplete works and no error is displayed when you manually type in the class name

![image](https://user-images.githubusercontent.com/2014500/107957615-8404df00-6fa9-11eb-8ff5-2693db3925c5.png)

## Your Environment

- Version used: 4.0.0
- vscode 1.53.2
- Operating System and versions: Windows 10
- Link to your project: (not public)

**Comment by skovy** [comment]
Hi @boformer, thanks for opening this issue!

Unfortunately, as you mentioned, this an issue with the way VSCode works and is not specific to this project. As a result, I don't believe the fix should live in this repo since I've seen this happen whenever a type definition is automatically changed (eg: git pulling file changes).

If you're willing to creating a VSCode extension, package that can be used, or something along those lines, I'd be happy to include something in the project/README for others facing this issue.
