### ISSUE TITLE
Update to dart-sass.

### ISSUE THREAD

**Issue by ruojianll** [skovy/typed-scss-modules#140]
Node-sass is deprecated now. Update package.json to dart-sass.

**Comment by skovy** [comment]
@ruojianll can you please elaborate? Yes, `node-sass` is deprecated but that doesn't mean nobody is using it. Removing it from this tool might mean some people that depend on it today would no longer be able to use it. Unfortunately, that means it'll need to be supported for a while. I do think it's reasonable in a major release to (eventually) remove support entirely for `node-sass`.

This package supports both `sass` (dart sass) and `node-sass`. It will default to whichever is in your `package.json` or explicitly passed, docs: https://github.com/skovy/typed-scss-modules#--implementation. This tool should work for both use cases (`sass` or `node-sass`) and doesn't have any drawbacks (as far as I know) by supporting both so I don't see the rush in removing `node-sass`.

**Comment by ruojianll** [comment]
Node-sass is in this repo's package.json, in my case this package has a crash while installing cause of it's node-sass dependency. And more installing issues will be found in the future. So I suggested remove node-sass from package.json.

**Comment by skovy** [comment]
Yes, it's in the development dependencies. Again, this is required for testing this package still behaves as expected for those that still rely on node-sass and should never be installed by this package as a consumer (if working on this package, then yes since it's a requirement to test and develop this package).

It is not a dependency, so it won't be installed when you install this package. It's marked as an optional peer dependency: https://docs.npmjs.com/cli/v7/configuring-npm/package-json#peerdependenciesmeta. 

From what I see, this is all working as expected and shouldn't be causing any issues. If it is causing issues, please open a new issue following the template with an actual error and reproducible example. Thank you.

**Comment by ImLunaHey** [comment]
>  so it won't be installed when you install this package.
that's exactly what's happening for me.
