### ISSUE TITLE
Feature request: Make --updateStaleOnly write only when generated type definition changed

### ISSUE THREAD

**Issue by raffomania** [skovy/typed-scss-modules#180]
## Expected Behavior

When running with `--updateStaleOnly`, compare the generated types with the types that are already present, and only re-write the type definitions if the new generated types differ.

## Current Behavior

At the moment, when I change a css property (e.g. `background-color`), the type definitions are re-written even though the contents remain the same. This triggers a typescript compilation, making my hot reload workflow slower than it could be.

## Possible Solution

By comparing generated types with the file contents that are already there, tsm could only touch the file when it really has to.

## Your Environment

- Version used: 6.4.1
- Operating System and versions: Arch Linux, Node 16.19.0

**Comment by skovy** [comment]
The way this currently works it's checking when the source style file was written versus the output type file. If the type file is newer, then it skips. Currently, there is no comparison of content, but it does seem reasonable when this option is enabled to compare contents of the type file and if identical skip. This would ignore changes to CSS properties since they don't affect the type output.

**Comment by skovy** [comment]
@raffomania can you try version `7.1.3` and confirm this resolves your issue?
