### ISSUE TITLE
Don't generate export for @keyframes

### ISSUE THREAD

**Issue by kostaskriaridis** [skovy/typed-scss-modules#190]
## Introduction
Hello, everyone 👋 
Thank you for supporting such a great tool 🙏 

## Expected Behavior
We have the following `.scss` file:
```
.root {
  animation: scale-animation 1.4s ease-in-out;
}

@keyframes scale-animation {
  0% {
    transform: scale(0);
  }

  100% {
    transform: scale(1);
  }
}
```

I expect tsm *not* to generate named export for `@keyframes` declaration

Desired output:
```
export const root: string;
```

## Current Behavior
Actual output:
```
export const root: string;
export const scaleAnimation: string;
```

## Possible Solution
1. Not to generate export for `@keyframes` declaration
2. Create a separate option for the package like `--excludeKeyframes`

## Context
1. I enabled `namedExport` option in `css-loader` webpack plugin
2. I enabled `import/no-unused-modules` eslint rule for `.scss.d.ts` files
3. In `.scss` files, where I have `@keyframes` declaration, animation name get's generated in `.scss.d.ts` files and I get an error from `import/no-unused-modules`, because this variable is not used in my react components

## Your Environment
- Version used: `7.0.2`
- Operating System and versions: `macOS Monterey, 12.6.1`
- Link to your project: [link](https://github.com/kostaskriaridis/typed-scss-modules-test)

**Comment by kostaskriaridis** [comment]
Hello, @skovy, thank you for your response

I created a test [Pull Request](https://github.com/skovy/typed-scss-modules/pull/191) where I use [css-tree](https://github.com/csstree/csstree) package for parsing css.

May you please have a look?

**Comment by skovy** [comment]
After doing some more research, this is actually intentional and supported behavior. Since someone could be using this and relying on it I don't think this is a bug, but intended functionality.

Example of how this can be used:

```css
@keyframes animate {
  0% {
    transform: scale(0);
  }

  100% {
    transform: scale(1);
  }
}
```

```js
import styles from "./style.css";

<div style={{ animation: styles.animate, }} />
```

This allows importing animations by name and applying them dynamically.

**Comment by jeron-diovis** [comment]
@skovy There is an issue in your example above.
Although css-modules themselves indeed automatically export keyframes along with classnames – but those names are transformed like everything else. So your `styles.animate` value will contain not an `animate` string but smth like `_animate_vl9dn_43`. Which obviously won't work (and makes me question why are they doing this in the first place). 

To use it like this you'll need to configure `getLocalIdent` option of css-loader - and probably follow some naming convention, to be able to recognize keyframes there and don't rename them. I really doubt someone will ever bother with this, when you can just apply animation in a class and export that class as usual.

---

But regardless, behaviour of typed-scss-module about generating types for keyframes is correct, because it fully matches to how css-modules work.
