### ISSUE TITLE
Feature request: option to output errors only or silence it completely?

### ISSUE THREAD

**Issue by lkarmelo** [skovy/typed-scss-modules#36]
I can work on this and send PR if you are ok with this

**Comment by skovy** [comment]
Yea, I think this makes sense.

I like the approach webpack takes here: https://webpack.js.org/configuration/other-options/#infrastructurelogginglevel

Thoughts on using this for inspiration and adding a new option `logLevel`. So the new entry in the README would look something like the following.

---

### `--logLevel` (`-l`)

- **Type**: `"verbose"` | `"errors"`
- **Default**: `"errors"`
- **Example**: `tsm src --logLevel verbose`

---

This would technically be a breaking change because to get the previous behavior you would now have to do `--logLevel verbose` but in a large project this feels _very_ verbose and most people likely only want to see errors when getting started?

Maybe we add `info` and make that the default and that would only print things like `Found 1 files. Generating type defintions...` to give confirmation (but not all the intermediary messages)? That would give `verbose`, `info` and `errors`?

**Comment by lkarmelo** [comment]
I was also thinking of using webpack as reference. `verbose`, `info`, `errors` options make sense to me, maybe even add `silent` option?

Why not make `verbose` default to preserve backwards compatibility? I am personally fine with either default options, just something to consider.

**Comment by skovy** [comment]
@lkarmelo yea that sounds good to me 👍 

`verbose` as the default is probably a good idea to make it easier when first getting started to understand what's happening

**Comment by halfnibble** [comment]
@peanutbother can you make a PR based on your --logLevel changes in your branch? Or do you mind if I use your code to make a PR?

**Comment by peanutbother** [comment]
feel free to create pull requests based of my fork - I currently don't have time to create clean PRs.
so far the code was accepted but my changes weren't clean because I fixed multiple issues.
I you want to, you can look into my PRs in my repo.

https://github.com/peanutbother/typed-scss-modules/issues?q=is%3Aissue+is%3Aclosed

@skovy could you add me and of course @halfnibble as contributors please?

**Comment by skovy** [comment]
@all-contributors please add @peanutbother for ideas
