### ISSUE TITLE
Undefined variable: "$screen". Typings creation crash

### ISSUE THREAD

**Issue by BiosBoy** [skovy/typed-scss-modules#59]
## Expected Behavior
Should transpile SCSS files which include some SASS variables like `$some_var` without any crashing. Like `css-modules-typescript-loader` it's actually do.
## Current Behavior
```
yarn tsm index.scss
Found 1 file. Generating type definitions...
ERROR: Undefined variable: "$screen". (/index.scss[43:27])

// index.scss
.buttonTitle {
  color: #628ba0;
  text-shadow: 1px 1px 1px rgba(255, 255, 255, .45);

  @media #{$screen} {
      top: 1px;
  }
}
```

## Your Environment

- Version used: 1.2.0
- Operating System and versions: macOS Mojave
- Link to your project: nope

**Comment by skovy** [comment]
Hey @BiosBoy, thanks for opening this issue!

From what I can tell this is the expected behavior. The difference between this tool and `css-modules-typescript-loader` (from what I understand) is that's working with only CSS and not SASS. With SASS, we have to run the compiler because class names can be dynamically generated or nested (eg: `.class { &-nested { color: red; } }`).

Therefore, to run the compiler it needs to be valid SASS so we can get the final classes that need types generated. Where is this variable? Would something like the proposed `includeFiles` (or something similar) discussed in https://github.com/skovy/typed-scss-modules/issues/29 work to resolve this issue for you as well?

If I'm misunderstanding, please create a minimum reproducible test case and we can re-open and investigate!

**Comment by BiosBoy** [comment]
Hi @skovy !
Thanks for a blazing fast response first of all and your project as well! 

Well, you're right `includeFiles` have solve my problem.  

I've also tried integrating the way `sass` recommend to, but it doesn't help for some reason. Btw I didn't make any deeper investigation than just put `sass.render` right on the `node-sass` initialization inside your **lib**: 
```
var sass = require('node-sass');

sass.render({
  data: '$my_module_global: "World"; .test { content: hi(); }',
  functions: {
    'hi($name: "nocanhazglobalhere")': function(name, done) {
      // How do I access global Sass variables like $my_module_global in here?
      done(sass.types.String('Hello, ' + name.getValue() + '!'));
    }
  }
}, function(error, result) {
  console.log(result ? result.css.toString() : error);
});
```

Cheers.
