### ISSUE TITLE
[FEATURE] Integrate with webpack.

### ISSUE THREAD

**Issue by ruojianll** [skovy/typed-scss-modules#98]
I'm working on webapck+ts+vue+jsx. I need typed scss module and inject it to jsx。 typed-scss-modules is great and work well. Bug is there any way to use it in webpack not in cli？

**Comment by ruojianll** [comment]
I wrote a simple webpack loader to do this. A outputDir option will make structure more pretty.
```
//loader.js
const { execSync } = require('child_process')
const path = require('path')
module.exports = function (content) {
    execSync(`${path.resolve('./')}/node_modules/.bin/tsm ${this.resource}`)
    this.callback(null, content)
}
```
```
//webpack config
{
  "module": {
    "rules": [
      {
        "test": {},
        "use": [
          {
            "loader": "loader.js"
          }
        ]
      }
    ]
  }
}
```

**Comment by skovy** [comment]
@ruojianll have you looked at https://github.com/Jimdo/typings-for-css-modules-loader?

From my understanding, this loader can be combined with the loader responsible for transpiling SASS to CSS. Since there's a tool that is already designed as a webpack plugin and handles this case, I'm going to close this issue.
